### ISSUE TITLE
v1.11.0 completely breaks (on some locales?)

### ISSUE THREAD

**Issue by tribut** [joelshepherd/tabliss#42]
When tabliss was updated to v1.11.0, this is the result:

![screenshot from 2018-03-27 17-13-53](https://user-images.githubusercontent.com/719105/37976855-b74d3266-31e2-11e8-9740-d11b15affa19.png)

This appears to have been introduced in 656e5587bca9fcd642c31a9dc157f92e55177ce0 and to be caused by https://github.com/joelshepherd/tabliss/blob/1828db20893f1d0800b73fe62cd0e11fd75bcb3a/src/utils/getConvertedDate.ts#L4-L15

`toLocaleString` returns `27. März 2018, 17:20:08` on my browser which `Date()` cannot parse.

**Comment by celiacheff** [comment]
Same here, on Firefox + Chrome on Linux.

**Comment by joelshepherd** [comment]
Ah thanks for reporting this. I needed to download Firefox again in another language to reproduce it. I'll have a fix out soon!

**Comment by joelshepherd** [comment]
I have now fixed the issue and pushed out a patched version 🙌

**Comment by tribut** [comment]
Great :tada: 
Don't forget to push the updated version to https://web.tabliss.io/, which appears to be still broken.

**Comment by joelshepherd** [comment]
I didn't have keys to deploy to the web version where I was earlier, but I have pushed it there now. (You may need to wait for the service worker to update for the changes to take effect)
