### ISSUE TITLE
[Bug] Error on loading images from Unsplash

### ISSUE THREAD

**Issue by KasiMaru** [joelshepherd/tabliss#78]
First of all thank you for the amazing extension! 

I've installed it just recently and everything was fine, and then all of a sudden images from Unsplash stopped loading (black screen). I'm getting ether 'Failed to load resource: net::ERR_FILE_NOT_FOUND 49f704f7-54c7-4a06-b860-cd2407945184:1', or 'GET blob:chrome-extension://hipekcciheckooncpjeljhnekcoolahp/3826e389-2d49-40ef-babc-30b4e6d7ecd2 0 ()' in the console. 

Even more weird is the fact that the URL in the bottom left corner won't update, even though I've set 'update image every new tab'. Links itself are working, in my case it's always 'Photo / Francesco Gallarotti / Unsplash'.

Also it seems that the settings for the images to change are not being saved, on each refresh they are being reverted to "refresh every 1 hour". Other settings are saving.

All other options (GIPHY, solid backgrounds) are working fine.

Tried to reinstall, disable - enable, no luck.

My browser is Google Chrome, version 67.0.3396.99 64-bit, Mac OS High Sierra. On latest Firefox Developer Edition everything is working no probs.

**Comment by joelshepherd** [comment]
Hi!

This is by far the most notorious bug I have in Tabliss, it has been reported and appears in my error logging for a while now, but I have no idea how to replicate it!

The way most people resolve it is using the "Tabliss is just a black background" support items here: https://tabliss.io/support.html

Its interesting you too previously had the "refresh every X" option set. A few other people have reported that and I'm starting to get a suspicion that's what causes it. But it always works for me everytime I try it :(

If anyone can figure out how to replicate it I would be very grateful!

**Comment by KasiMaru** [comment]
Well, I've done *something* and now Unsplash API is working again. 

Problem is, I've done many things erratically and can't figure out what fixed it 😅. Also I can't replicate it now. 

If the problem will appear again I'll make sure to at least document steps I'm doing to solve it and will post here. 

Sorry I can't be of any use for now.

**Comment by KasiMaru** [comment]
It happened again out of nowhere, still don't know what's the deal.

However, I know how to fix it, temporary at least. If the image is not loading you have to check the radio button "Custom collection" in the settings. That fixes loading and you can revert back to "Official collection".

<img width="296" alt="new_tab" src="https://user-images.githubusercontent.com/26373955/42799048-f406e8be-899e-11e8-99e6-f3d9be060a75.png">

**Comment by joelshepherd** [comment]
And this time you had "Every new tab" on, so it couldn't be just related to the "change every X" rule :(

**Comment by iskrisis** [comment]
Hi @joelshepherd i dont use tabliss but when trying web version i got the black background. By coincidence i've noticed this issue when i skimmed the repo.

The reason for it is that Unsplash api endpoints are blacklisted in adblockers and tracker blockers as trackers (probably correctly). It is probably not so visible in newtab but i believe the blockers work there aswell. When i disable them everything starts to work fine. Maybe you don't block trackers so you never get this issue. Also the wierd thing is that not every time the Unsplash endpoint gets blocked as tracker. Are you including any unsplash js helper library? Or are those just api calls?

**Comment by Tester798** [comment]
Previously got this bug only once long time ago. But today I got it again. Seems like for me it happened because Chrome browser didn't write indexeddb files with images to the disk (probably because I killed the process manually, but I suspect it can happen in other rare cases too). So the file was missing and I started to get black screen.

Here is how to reproduce the bug:
1. In options set "Show a new photo" to "Every 15 minutes"
2. Get blob url of the image showed on new tab:
> ![image](https://user-images.githubusercontent.com/8844478/45580433-b1f60e80-b899-11e8-94b6-f13bbe01f565.png)
3. Open chrome://blob-internals/ and at the bottom find same blob (1) and its uuid (2):
> ![image](https://user-images.githubusercontent.com/8844478/45580498-59734100-b89a-11e8-9d13-a4a2bd6caf95.png)
4. Above by the uuid (3) find location of the blob files (4):
> ![image](https://user-images.githubusercontent.com/8844478/45580553-1e254200-b89b-11e8-9cde-f477f14b9685.png)
5. Go to the found folder and delete all files in it. Get black screen on new tab

It can be fixed pretty easily by changing collection in options, but it would be nice if extension could detect this error automatically and fix itself (maybe by checking load error):
> ![image](https://user-images.githubusercontent.com/8844478/45580619-f4204f80-b89b-11e8-91f5-2c77740aa6f9.png)

**Comment by joelshepherd** [comment]
Thanks for the reproduction steps!

I will have a play around with this soon and see if I can catch these errors and have it automatically refetch new Unsplash images.

**Comment by Vizionz-Project** [comment]
Thanks for this extension, looks like this can really help me. Question can we put a music player into the custom js without issue?

**Comment by trickypr** [comment]
You should check if there is an issue on this already, if not create an issue.

**Comment by Tester798** [comment]
Got this bug few more times, very annoying:
![image](https://user-images.githubusercontent.com/8844478/53690457-6a920a80-3d73-11e9-895f-4624235a8492.png)

Also noticed that not every time this issue can be solved by changing collection in options: sometimes it loads new image, but after refreshing the page it's showing black background again. In this case, only reinstalling the extension helped, with loosing all settings.

**Comment by bafulton** [comment]
I'm not sure the black screen bug has been fixed by PR 118. I just ran into the bug for the first time in the past few days. For now, uninstalling and reinstalling the extension has fixed it. I'll update you if it happens again.

**Comment by joelshepherd** [comment]
Ah I just realised I forgot to release this 🤦‍♂ I'll prepare for a release tonight!

**Comment by D3S0X** [comment]
I got this bug running Tabliss 1.18.1 on Google Chrome 79.0.3945.88 using Arch Linux.
Changing collection to custom and back to official or time interval didn't fix it for me. It just went back to the picture it was staying on before.
I followed the instructions by @Tester798 and deleted

- chrome-extension_hipekcciheckooncpjeljhnekcoolahp_0.indexeddb.blob
- chrome-extension_hipekcciheckooncpjeljhnekcoolahp_0.indexeddb.leveldb

in ~/.config/google-chrome/Default/IndexedDB/
restarted Chrome and now it's getting new images again

Just wanted to let you know I'm sorry but I can't provide any logs or how to reproduce it

**Comment by rghvv** [comment]
I just got this bug running Tabliss 2.0.3 on Firefox 77.0.1 using MacOS 10.15.5. Everything else (GIPHY, gradient, custom images) seems to work fine.

In the console, I get "TypeError: u.urls is undefined" in main.js.

I believe the error lies in:

`case 2:
    return u = s.sent(), [4, fetch(u.urls.raw + "?q=85&w=1920")];`
